
import { GluegunToolbox } from 'gluegun'

module.exports = {
  name: 'create',
  alias: 'c',
  description: 'Creates a new base project.',
  run: async (toolbox: GluegunToolbox) => {
    toolbox.create('app', [
      { file: 'common/test/fixtures/mockup.model' },
      { file: 'common/test/fixtures/mockup.routes' },
      { file: 'common/test/fixtures/mockup.sockets' },
      { file: 'common/test/mockup.test' },
      { file: 'common/test/utils.test' },
      { file: 'common/environment' },
      { file: 'common/router-base' },
      { file: 'common/router' },
      { file: 'common/socket-base' },
      { file: 'common/utils' },
      { file: 'jobs/notify/event' },
      { file: 'plugins/i18next/locales/pt-BR/index' },
      { file: 'plugins/i18next/locales/pt-BR/joi18n' },
      { file: 'plugins/i18next/locales/index' },
      { file: 'plugins/i18next/index' },
      { file: 'plugins/passport/strategies/authHeader' },
      { file: 'plugins/passport/strategies/urlQuery' },
      { file: 'plugins/passport/confirmation' },
      { file: 'plugins/passport/index' },
      { file: 'plugins/passport/validation' },
      { file: 'plugins/redis/client' },
      { file: 'plugins/redis/index' },
      { file: 'plugins/restify-joi-middleware/index' },
      { file: 'plugins/restify-render-middleware/index' },
      { file: 'server/error.handler' },
      { file: 'server/index' },
      { file: 'server/merge-patch.parser' },
      { file: 'types/default/index', ext: 'd.ts' },
      { file: 'views/home', ext: 'pug' },
      { file: 'views/layout', ext: 'pug' },
      { file: 'common-services', ext: 'yml' },
      { file: 'docker-compose', ext: 'yml' },
      { file: 'docker-compose.stage', ext: 'yml' },
      { file: 'env.example', prefix: '.', ext: '' },
      { file: 'gitignore', prefix: '.', ext: '' },
      { file: 'jest.startup' },
      { file: 'main' },
      { file: 'main.routes' },
      { file: 'makefile', rename: 'Makefile', ext: '' },
      { file: 'package', ext: 'json' },
      { file: 'readme', rename: 'README', ext: 'md' },
      { file: 'tsconfig', ext: 'json' },
    ])
  }
}
